"""
Embed world.jpg as a base64 data URL into world-texture.js and patch
weather-os.html so the globe texture also works when opened directly with the
file:// protocol.

Run from this folder (or from any working directory) after placing world.jpg
beside this script:

    python3 embed_texture.py
"""
from __future__ import annotations

import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent
JPG_PATH = ROOT / "world.jpg"
HTML_PATH = ROOT / "weather-os.html"
JS_PATH = ROOT / "world-texture.js"
DONE_PATH = ROOT / "embed_done.txt"
SCRIPT_TAG = '<script src="./world-texture.js"></script>'
FALLBACK_SRC = 'img.src = window.WORLD_JPG_DATA_URL || "./world.jpg";'
LEGACY_SRC_SINGLE = "img.src='./world.jpg';"
LEGACY_SRC_DOUBLE = 'img.src="./world.jpg";'


def patch_html(html: str) -> str:
    """Add the companion script tag and make legacy texture loaders data-aware."""
    if SCRIPT_TAG not in html:
        html = html.replace("<head>", "<head>\n    " + SCRIPT_TAG, 1)

    # Support both the current formatted source and the original unformatted line
    # from the one-file prototype.
    html = html.replace(LEGACY_SRC_SINGLE, FALLBACK_SRC)
    html = html.replace(LEGACY_SRC_DOUBLE, FALLBACK_SRC)
    return html


def main() -> None:
    try:
        jpg_bytes = JPG_PATH.read_bytes()
        data_url = "data:image/jpeg;base64," + base64.b64encode(jpg_bytes).decode("ascii")

        JS_PATH.write_text(
            "// Auto-generated by embed_texture.py — do not edit manually\n"
            f"window.WORLD_JPG_DATA_URL={data_url!r};\n",
            encoding="utf-8",
        )

        html = HTML_PATH.read_text(encoding="utf-8")
        HTML_PATH.write_text(patch_html(html), encoding="utf-8")

        DONE_PATH.write_text(
            f"SUCCESS\njpg_bytes={len(jpg_bytes)}\ndata_url_len={len(data_url)}\n",
            encoding="utf-8",
        )
        print("Done! world-texture.js written and weather-os.html patched.")
    except Exception as exc:  # Keep Chromebook double-click workflows diagnosable.
        DONE_PATH.write_text(f"ERROR: {exc}\n", encoding="utf-8")
        print("Error:", exc)
        raise


if __name__ == "__main__":
    main()
